### ISSUE TITLE
syntax checked `write!` macro

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#104]
for now the `write!` macro has been removed from the public API because it's too free form.
We'll need the `write!` macro for things like `svd2rust` integration (`derive` is not flexible enough) so we want a public `write!` macro but that's syntax checked: the format string should be a valid struct ("S {{ field: {:u8} }} }") or valid enum.

We can start with just checked struct syntax. enum syntax is a bit harder: how do we want to expose it to the user so that they cannot misuse?

**Comment by jonas-schievink** [comment]
We can also allow a fully free-form `write!` macro that uses a different tag (in the symbol name) from the derive macro. This allows arbitrary user-defined `Format` implementations, while still letting us make assumptions about `#[derive]`d implementations.

On the decoder side, we'd have to avoid interpreting `|`s in such strings (and anything else we might do).

**Comment by jonas-schievink** [comment]
Do we want to allow multiple `write!` invocations in a `Format` impl?

If so, this requires decoder changes, which means users will have to reinstall probe-run (not sure if we should count this is as a breaking change, but probably). My plan here was to let the decoder read string indices in a loop, as long as their tag is `Write`.

If not, we have to forbid this at runtime, since `write!` will work on a `&mut Formatter`, which can be duplicated by reborrowing (or we'd have to change the parameters `Format::format` takes, which is also breaking).

**Comment by japaric** [comment]
I'd say the criteria for deciding if something is a breaking change or not is: if we release this in a new patch release (e.g. defmt 0.1.2) will a currently installed probe-run (e.g. 0.1.4 + decoder 0.1.4) continue to work? If the answer is *no* then it's a breaking change.

Adding a new "tag" variant does sound like a breaking change. Could we reuse the existing `Fmt` tag for this somehow?

If we need to add a runtime check to `write!` (via some internal boolean flag) to ship this in the 0.1.x series then I'd be fine with that.
