### ISSUE TITLE
RFC: Structured symbol names

### ISSUE THREAD

**Issue by jonas-schievink** [knurling-rs/defmt#108]
Currently, the logging macros each place their format string in a different section depending on the log level. The symbol name is set to the format string (and "versioned" using the call-site span, to prevent multiple identical logger calls from creating symbol conflicts). Instead, binfmt could all place the format strings in the same section, but use a more structured symbol name that also contains the logging level.

This allows users to extend binfmt with custom (non-logging) data. Other crates could define their own tags and transfer custom data using the binfmt transport, without actually having to pay any multiplexing overhead. This is helpful for the planned graphing library. The binfmt tooling can also detect and skip non-logging frames.

**Comment by steveklabnik** [comment]
I *think* that this fits here...

I am interested in using defmt in an OS, with multiple tasks. Right now, this means that the string indices collide. I believe this would allow me to solve this pretty easily by tagging each log frame with the task id.

**Comment by japaric** [comment]
> I am interested in using defmt in an OS, with multiple tasks. Right now, this means that the string indices collide

Could you give more details about how these collisions *manifest*? Are they runtime collisions? link time errors?
By collision do you mean that you cannot visualize differentiate from the output which task produced which log? Would changing the log statements to `info!("[task {:u32}] (..)", task::current_id(), /* .. */)` help?
Or do you mean something else?
If we are talking about a *multi-process* OS where one ELF file (Rust program) can be spawned as its own process then I can see how the string indices would "collide" (get misinterpreted by the decoder). Is that your use case?

**Comment by steveklabnik** [comment]
Ah, sorry, yeah. Lots of details matter here, sorry to not be more clear.

> If we are talking about a multi-process OS where one ELF file (Rust program) can be spawned as its own process

Yeah so, our OS is a hybrid system; at compile time, you say every task that exists, and they cannot be created or destroyed, just started, stopped, and restarted. That said, they are compiled into separate elf files, and the whole image is created out of them. This means that two different tasks will both have their first log message at index zero, which means that the program interpreting the output of defmt would not understand which "index zero" to use to deserialize.

> Would changing the log statements to info!("[task {:u32}] (..)", task::current_id(), /* .. */) help?

In some sense, yes. In order for this to work consistently, this would mean that I would have to write my own wrapper macro, which isn't the end of the world. It also is the basic difference between logging and structured logging; you can always interpret the data into the message and parse it out later, but structured logging treats this as more of a first-class thing.

**Comment by japaric** [comment]
Thanks for the details I can now see the issue more clearly.

It seems that this feature should help if we allow adding timestamp-like metadata to the log frame. So your the log frame customized for your use case would be something like: `[task_id, timestamp, format_string_index, $args]`. I think you would still need some like `info!(task_id=1, "hello)` in the program side (or maybe $crate_name instead of the `1` there).

Then you'll need a custom `probe-run` tool that reads many ELF files, creates a map from task_id to string tables and then decodes the log frames differently: you'll want to decode the task id first to decide which string table to use, then you decode the rest of the frame as it's done today.

In any case, it seems to me that you'll need to use `defmt` as a library rather than directly use `probe-run` as you have a rather particular use case: `my-probe-run elf1 elf2 ..`

> they are compiled into separate elf files, and the whole image is created out of them

if you could merge all the ELF files into one and adjust the string indices in this step then I think that you might be able to use `probe-run` as it is today.

**Comment by steveklabnik** [comment]
> In any case, it seems to me that you'll need to use defmt as a library rather than directly use probe-run 

Yep, this is true! We already cannot use probe-run, so I am always assuming that the consumption side is using defmt as a library. Shoulda specified that too, argh 😄
