### ISSUE TITLE
impl Format for T where T: Debug

### ISSUE THREAD

**Issue by mattico** [knurling-rs/defmt#126]
I understand the motivation behind the custom `Format` trait. However, some of us have 2MB of flash and want to format library types which only `impl Debug`. It would be nice to provide an opt-in way to do this.

**Comment by jonas-schievink** [comment]
It seems to me that this isn't necessarily correctly implementable with buffering, since any fixed buffer size we choose might be too low for some `Debug` impls.

Could we somehow use the defmt sink as a `core::fmt::Write` implementation instead, and add first-class support for streams of unknown size to defmt? That way we wouldn't have to do any additional buffering and could work with *all* `Debug` implementors, no matter how long the output is.

**Comment by jamesmunns** [comment]
As a note, we might want to make this feature opt-in, at least at an application level
