### ISSUE TITLE
Release alpha version to crates.io

### ISSUE THREAD

**Issue by MathiasKoch** [knurling-rs/defmt#146]
Hi.

Would it be possible to do an alpha release to crates.io, as it is not possible to publish crates containing git dependencies.

**Comment by Lotterleben** [comment]
Hi Mathias,
just a heads up because it's been a while– we didn't want to publish defmt to crates.io before some critical known issues are fixed. We're currently in the process of doing that because we too want to remove this hurdle. I'll keep you posted and close this issue once defmt is on crates.io :)

**Comment by jamesmunns** [comment]
Hey @MathiasKoch, we've released a version of 0.1.0 of defmt and related tools to crates.io, so this issue should be good to close!
