### ISSUE TITLE
const generics tracking issue

### ISSUE THREAD

**Issue by Urhengulas** [knurling-rs/defmt#429]
Since const generics will hit stable soon ([blog](https://blog.rust-lang.org/2021/02/26/const-generics-mvp-beta.html)), I started thinking about where we could use it and would like to track this in this issue.

**List**
- [ ] remove code duplication in `src/impls.rs`
  - [ ] arrays
  - [ ] ...
- [ ] ...

**Comment by jonas-schievink** [comment]
We can't actually get rid of the duplication for arrays that easily, because every array length has a different format string, which is a literal.

However we could change how arrays work, and instead send the array length over the wire instead of encoding it in the format string. It would be somewhat less efficient but might be fine.

**Comment by jonas-schievink** [comment]
We could actually keep the length in the format string for short arrays and send it over the wire for longer arrays. That way we could use const generics to implement `Format` for arrays of any size, without losing the efficiency of the current implementation.
