### ISSUE TITLE
Defmt's dbg! implementation fails clippy::double_parens

### ISSUE THREAD

**Issue by DusterTheFirst** [knurling-rs/defmt#642]
When using the dbg! macro in a function call, the macro expansion seems to flag a clippy lint. [clippy::double_parens](https://rust-lang.github.io/rust-clippy/master/#double_parens) to be specific.

![image](https://user-images.githubusercontent.com/14093962/143765135-18ef1393-81f0-4f06-ae01-c40e55ab3416.png)

**Comment by Urhengulas** [comment]
This is more of a clippy, than a defmt issue. In best case clippy would ignore lints from foreign macros, since as a user you have limited control over the expansion. See https://github.com/rust-lang/rust-clippy/issues/407 for more information.

As a workaround you can silence the warning by adding an allow-statement before the macro call:
```rust
#[allow(clippy::double_parens)]
function(defmt::dbg!(a));
```
